### ISSUE TITLE
Add new Instruments & allow user to choose

### ISSUE THREAD

**Issue by eridgers** [eridgers/tune-your-ears#2]
User should be able to select instrument they wish to train/play on.
The following is required for this functionality:

- [x] Add user input drop down list to select instrument #3
- [x] Display which instrument is currently selected #4 
- [x] Populate list with available instruments #5 
- [x] Prepare and add sounds files for extra instruments. (current folder structure ok?) #6
- [x] Push new sounds to notes array (sprite for each instrument?) #7 
- [x] Play sound based on instrument & notePicked #8 
- [x] When instrument selected, update note display (e.g. E on box 1 for guitar) #9 
- [x] Change display boxes to match number of notes (e.g. from 6 for guitar to 4 for bass) #10 
- [x] Update pickNote based on instrument (number of strings) #11 
- [x] Redesign Level #12
